CREATE OR REPLACE FUNCTION HR_GET_DEPARTMENT_DETAILS
RETURN SYS_REFCURSOR
IS
department_details SYS_REFCURSOR;
BEGIN
  OPEN department_details FOR select * from HR_DEPARTMENT;

  RETURN department_details;

END HR_GET_DEPARTMENT_DETAILS;

 
/
